In [1]:
# numpy is great for doing vector arithmetic.
# numpy stands for numeric pyhton.
# numpy array can not contain elements with different data types.
# If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list. This is known as type coercion.
#
import numpy as np

In [8]:
x = [range(100)]

In [10]:
print (type(x))

<class 'list'>


In [13]:
print (x)

[range(0, 100)]


In [14]:
np_x = np.array(x)

In [15]:
print(np_x)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
  48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
  72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
  96 97 98 99]]


In [16]:
np_greater_than_25 = np_x > 25

In [17]:
print (np_greater_than_25)

[[False False False False False False False False False False False False
  False False False False False False False False False False False False
  False False  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True  True]]


In [18]:
np_2d_array = np.array([[1,2,3,4,5],
                       [6,7,8,9,10]])

In [19]:
np_2d_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
np_2d_array.shape

(2, 5)

In [29]:
np_3d_array = np.array([[[1,2,3,4,5],
                         [6,7,8,9,10],
                         [11,12,13,14,15]]])

In [30]:
np_3d_array.shape

(1, 3, 5)

In [31]:
np_3d_array

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [32]:
np_3d_array[0][0]

array([1, 2, 3, 4, 5])

In [33]:
np_3d_array[0][0][0]

1

In [34]:
np_3d_array[0][1]

array([ 6,  7,  8,  9, 10])